### ISSUE TITLE
Getting KeyError for REDIS_URL

### ISSUE THREAD

**Issue by Rahul108** [veryacademy/YT-Django-Project-Chatroom-Getting-Started#2]
Getting the following error when I'm trying to migrate or run this project

```sh
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/prefix108/Documents/Projects/YT-Django-Project-Chatroom-Getting-Started/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/prefix108/Documents/Projects/YT-Django-Project-Chatroom-Getting-Started/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/home/prefix108/Documents/Projects/YT-Django-Project-Chatroom-Getting-Started/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/prefix108/Documents/Projects/YT-Django-Project-Chatroom-Getting-Started/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/prefix108/Documents/Projects/YT-Django-Project-Chatroom-Getting-Started/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/prefix108/Documents/Projects/YT-Django-Project-Chatroom-Getting-Started/core/settings.py", line 130, in <module>
    "hosts": [os.environ['REDIS_URL']],
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'REDIS_URL'
```

Tried to solve this issue by installing `channels-redis`, `django-redis`

Also tried with an .env file, getting the same result

What am I doing wrong?

**Comment by Rahul108** [comment]
Able to run properly when I used `("127.0.0.1", 6379)` instead of `os.environ['REDIS_URL']`
